### PR TITLE
Run lettuce against prod release

### PR DESCRIPTION
**Pull request by aahunter**
Allows lettuce to be run against a prod build using an nginx and uwsgi stack. A few other minor improvements; config to choose browser in lettuce, clean up anonymous volumes, parameterise url used by lettuce.

Also created a dedicated docker-entrypoint for the build image - the rebuilds after editing the dev/test entrypoint was slowing me down.

### CODE REVIEW

**Comment by aahunter** [comment]
Added an --interactive option so it is easy to run a specific feature file in dev. Run each of these in a different shell:

```
docker-compose -f docker-compose-teststack.yml up
docker-compose -f docker-compose-selenium.yml up
docker-compose -f docker-compose-lettuce.yml run devlettuce lettuce --interactive
```

You will be prompted for the feature file to invoke.

**Comment by id2359** [comment]
Idea seems good although might be good to have a command to run by featurefile name also.

When I run an interactively chosen test I'm getting import errors though:
Exception: Registry 'dd' already exists.
    Given export "dd.zip"                                                                # app/rdrf/rdrf/steps.py:94us 1
    Traceback (most recent call last):
      File "/env/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/app/rdrf/rdrf/steps.py", line 105, in load_export
        import_registry(export_name)
      File "/app/rdrf/rdrf/steps.py", line 68, in import_registry
        subprocess.check_call(["django-admin.py", "import", "/app/rdrf/rdrf/features/exported_data/%s" % export_name])
      File "/usr/local/lib/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    CalledProcessError: Command '['django-admin.py', 'import', u'/app/rdrf/rdrf/features/exported_data/dd.zip']' returned non-zero exit status 1

**Comment by id2359** [comment]
Despite the error, I see all passing steps though

 1 feature (1 passed)
1 scenario (1 passed)
19 steps (19 passed)

odd

**Comment by aahunter** [comment]
Before oyur run, clean up old volumes:

`docker-compose -f docker-compose-teststack.yml rm --force -v`

**Comment by aahunter** [comment]
To run a single feature file:

`docker-compose -f docker-compose-lettuce.yml run devlettuce lettuce --feature add_patient.feature`

(Assuming you've got selenium and a clean test stack running)

**Comment by id2359** [comment]
approved , but we'll have to re-introduce clean_models or some equivalent to enable running multiple invocations of either the lettuce interactive command or feature by name command

**Comment by sztamas** [comment]
What if we just changed the setup code to restore the minimal snapshot if it already exists, else take the minimal snapshot?
That way if you invoked run_lettuce more than once it will re-use the minimal snapshot created by the first invocation.
When we call ``./develop.sh lettuce`` we already rm the teststack/postgres and teststack/mongo containers, so the minimal snapshot will be taken on an empty db.

**Comment by aahunter** [comment]
The initial db state inconsistency should be handled 'upstream' (ie not Python). The tests should be able to kick off assuming the db is in a valid initial state (ie post clean django migrate). It is not an issue created by this PR, so merging and will make that change in another PR.

**Pull request merged**
