### PR TITLE
RDR 1358 remove suits

### PR DESCRIPTION
**Pull request by aahunter**
suits isn't installed but lingering references remain, removed references

### CODE REVIEW

**Comment by id2359** [comment]
sounds like a good idea - just fyi we do still use the admin interface though

**Comment by aahunter** [comment]
@id2359  Can you point me to somewhere these changes might be a problem?

**Comment by id2359** [comment]
Looks like Maciej has cleaned up pages linked from Admin Pages but you could try http://localhost:8000/admin/groups/customuser/ for a test - I can't find suit referenced on the pages I've tested locallly just now so should be ok.

**Comment by id2359** [comment]
only the error pages were using ( which you fixed) - so ok

**Pull request merged**
