### PR TITLE
Python 3.5 and Django 1.10

### PR DESCRIPTION
**Pull request by rvl**
Related changes are grouped into separate commits. It would probably be less confusing for you to review each commit individually. For that, use `git fetch && gitk origin/python3`.

### CODE REVIEW

**Comment by rvl** [comment]
Looks like it works with your fixup.

I will merge when we're ready.

There are probably a few more bugs hiding which we should find soon enough...

**Comment by aahunter** [comment]
lgtm, made some trivial changes. Lee and Maciej are testing locally.

**Comment by mradochonski** [comment]
runserver_1  | Traceback (most recent call last):
runserver_1  |   File "/env/bin/django-admin.py", line 5, in <module>
runserver_1  |     management.execute_from_command_line()
runserver_1  |   File "/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
runserver_1  |     utility.execute()
runserver_1  |   File "/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
runserver_1  |     django.setup()
runserver_1  |   File "/env/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
runserver_1  |     apps.populate(settings.INSTALLED_APPS)
runserver_1  |   File "/env/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
runserver_1  |     app_config.import_models(all_models)
runserver_1  |   File "/env/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
runserver_1  |     self.models_module = import_module(models_module_name)
runserver_1  |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
runserver_1  |     __import__(name)
runserver_1  |   File "/app/rdrf/rdrf/registry/patients/models.py", line 15, in <module>
runserver_1  |     from rdrf.dynamic_data import DynamicDataWrapper
runserver_1  |   File "/app/rdrf/rdrf/rdrf/dynamic_data.py", line 3, in <module>
runserver_1  |     from itertools import zip_longest
runserver_1  | ImportError: cannot import name zip_longest

**Comment by aahunter** [comment]
@mradochonski Something doesn't look right there, the stacktrace is showing python 2.7, I would suggest docker rmi all your rdrf images and rebuilding.

**Comment by mradochonski** [comment]
After running it locally, all seem to be working.

**Pull request closed without merging**
